
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- cluster.ax1.openstack
- cluster.ax1.stacklight
- cluster.ax1.stacklight.client
- cluster.ax1.cicd
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2

    # infra service addresses
    infra_config_hostname: salt-master
    infra_config_address: 192.168.203.90
    infra_config_deploy_address: 192.168.201.4

    cluster_domain: axlab.local
    cluster_name: ax1
    cluster_public_host: ${_param:openstack_proxy_address}
    infra_kvm_address: 192.168.203.240
    infra_kvm_node01_address: 192.168.203.241
    infra_kvm_node02_address: 192.168.203.242
    infra_kvm_node03_address: 192.168.203.243
    infra_kvm_node01_deploy_address: 192.168.201.11
    infra_kvm_node02_deploy_address: 192.168.201.12
    infra_kvm_node03_deploy_address: 192.168.201.13
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0
    control_vlan: 10
    tenant_vlan: 20

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      gateway: ${_param:control_network_gateway}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}


  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_compute_node01_address}
          names:
          - ${_param:infra_compute_node01_hostname}
          - ${_param:infra_compute_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_compute_node02_address}
          names:
          - ${_param:infra_compute_node02_hostname}
          - ${_param:infra_compute_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_compute_node03_address}
          names:
          - ${_param:infra_compute_node03_hostname}
          - ${_param:infra_compute_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
